baseURL = "https://ebustamante.dev/"
languageCode = "en-us"
title = "Eduardo Bustamante | Cybersecurity Student & SOC Analyst"
theme = "ebustamante"

[params]
  description = "Cybersecurity student at UNOmaha. SOC Analyst Intern focused on Detection Engineering. Exploring ARM malware analysis, and other blue team topics."
  status = "UNO · Omaha, NE"
  certs_in_progress = 1
  tools_and_technologies = 24

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
[outputs]
  home = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[taxonomies]
  tag = "tags"

[related]
  includeNewer = true
  threshold = 50
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100