# Generated by Django 4.2.30 on 2026-06-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='writeups', to='core.tag')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
