# Generated by Django 4.2.30 on 2026-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
